[project]
name = "nlba"
version = "0.1.0"
description = "Natural Language Bash Assistant"
authors = [{ name = "Artyomka", email = "artyomka@example.com" }]
dependencies = []
requires-python = ">=3.9"

[build-system]
requires = ["uv>=0.1.0"]
build-backend = "uv.build"

[tool.uv]
src = "src"
